apiVersion: skaffold/v4beta3
kind: Config

manifests:
  rawYaml:
    - infra/k8s/*

build:
  local:
    push: false

  artifacts:
    - image: seniorigortyapkin/client
      context: .
      docker:
        dockerfile: apps/client/Dockerfile

    - image: seniorigortyapkin/auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile
