apiVersion: skaffold/v4beta3
kind: Config

# =========================
# DEFAULT = DEV
# =========================
manifests:
  rawYaml:
    - infra/k8s/env/dev/*.yaml
    - infra/k8s/base/*.yaml

build:
  local:
    push: false

  artifacts:
    - image: seniorigortyapkin/client
      context: .
      docker:
        dockerfile: apps/client/Dockerfile.dev
      sync:
        manual:
          - src: apps/client/**/*
            dest: .

    - image: seniorigortyapkin/auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile.dev
      sync:
        manual:
          - src: apps/auth/**/*
            dest: .
          - src: packages/core/**/*
            dest: .

# =========================
# PROD PROFILE
# =========================
profiles:
  - name: prod
    manifests:
      rawYaml:
        - infra/k8s/env/prod/*.yaml
        - infra/k8s/base/*.yaml

    build:
      local:
        push: false
      artifacts:
        - image: seniorigortyapkin/client
          context: .
          docker:
            dockerfile: apps/client/Dockerfile

        - image: seniorigortyapkin/auth
          context: .
          docker:
            dockerfile: apps/auth/Dockerfile
