apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing-prod

resources:
  - ../prod-common
  - ../../base/auth-mongo
  - ../../base/orders-mongo
  - ../../base/payments-mongo
  - ../../base/tickets-mongo
  - ../../base/event-bus
  - ../../base/redis
  - ../../base/event-bus-bootstrap
