FROM node:24.11.1-slim

WORKDIR /app

RUN npm i -g npm@11.6.2

# Install deps once
COPY package.json package-lock.json ./
COPY nx.json tsconfig.base.json ./

ENV HUSKY=0
RUN --mount=type=cache,target=/root/.npm npm ci

COPY apps/auth ./apps/auth
COPY packages/core ./packages/core

ENV NODE_ENV=development

CMD ["npx", "nx", "run", "auth:dev"]
