apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing

build:
  local:
    push: false
  artifacts:
    - image: seniorigortyapkin/client
      context: .
      docker:
        dockerfile: apps/client/Dockerfile.dev
      sync:
        manual:
          - src: apps/client/**/*
            dest: .
    - image: seniorigortyapkin/auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile.dev
      sync:
        manual:
          - src: apps/auth/**/*
            dest: .
          - src: packages/core/**/*
            dest: .
    - image: seniorigortyapkin/tickets
      context: .
      docker:
        dockerfile: apps/tickets/Dockerfile.dev
      sync:
        manual:
          - src: apps/tickets/**/*
            dest: .
          - src: packages/core/**/*
            dest: .
          - src: packages/nats/**/*
            dest: .
          - src: packages/contracts/**/*
            dest: .
    - image: seniorigortyapkin/orders
      context: .
      docker:
        dockerfile: apps/orders/Dockerfile.dev
      sync:
        manual:
          - src: apps/orders/**/*
            dest: .
          - src: packages/core/**/*
            dest: .
          - src: packages/nats/**/*
            dest: .
          - src: packages/contracts/**/*
            dest: .

manifests:
  kustomize:
    paths:
      - infra/k8s/apps/ticketing/overlays/dev

deploy:
  kubectl: {}

profiles:
  - name: prod
    build:
      local:
        push: false
      artifacts:
        - image: seniorigortyapkin/client
          context: .
          docker:
            dockerfile: apps/client/Dockerfile
        - image: seniorigortyapkin/auth
          context: .
          docker:
            dockerfile: apps/auth/Dockerfile
        - image: seniorigortyapkin/tickets
          context: .
          docker:
            dockerfile: apps/tickets/Dockerfile
    manifests:
      kustomize:
        paths:
          - infra/k8s/apps/ticketing/overlays/prod