apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing

build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: ghcr.io/seniorigor/ticketing-client
      context: .
      docker:
        dockerfile: apps/client/Dockerfile.dev

    - image: ghcr.io/seniorigor/ticketing-auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile.dev

    - image: ghcr.io/seniorigor/ticketing-tickets
      context: .
      docker:
        dockerfile: apps/tickets/Dockerfile.dev

    - image: ghcr.io/seniorigor/ticketing-orders
      context: .
      docker:
        dockerfile: apps/orders/Dockerfile.dev

    - image: ghcr.io/seniorigor/ticketing-expiration
      context: .
      docker:
        dockerfile: apps/expiration/Dockerfile.dev

    - image: ghcr.io/seniorigor/ticketing-payments
      context: .
      docker:
        dockerfile: apps/payments/Dockerfile.dev

    - image: ghcr.io/seniorigor/ticketing-event-bus-bootstrap
      context: .
      docker:
        dockerfile: apps/event-bus-bootstrap/Dockerfile.dev

manifests:
  kustomize:
    paths:
      - infra/k8s/apps/ticketing/overlays/dev-app

deploy:
  kubectl: {}

profiles:
  - name: dev-infra
    manifests:
      kustomize:
        paths:
          - infra/k8s/apps/ticketing/overlays/dev-infra
  - name: prod-images
    build:
      platforms:
        - linux/amd64
      local:
        push: false
        useBuildkit: true
      artifacts:
        - image: ghcr.io/seniorigor/ticketing-client
          context: .
          docker:
            dockerfile: apps/client/Dockerfile
        - image: ghcr.io/seniorigor/ticketing-auth
          context: .
          docker:
            dockerfile: apps/auth/Dockerfile
        - image: ghcr.io/seniorigor/ticketing-tickets
          context: .
          docker:
            dockerfile: apps/tickets/Dockerfile
        - image: ghcr.io/seniorigor/ticketing-orders
          context: .
          docker:
            dockerfile: apps/orders/Dockerfile
        - image: ghcr.io/seniorigor/ticketing-expiration
          context: .
          docker:
            dockerfile: apps/expiration/Dockerfile
        - image: ghcr.io/seniorigor/ticketing-payments
          context: .
          docker:
            dockerfile: apps/payments/Dockerfile
        - image: ghcr.io/seniorigor/ticketing-event-bus-bootstrap
          context: .
          docker:
            dockerfile: apps/event-bus-bootstrap/Dockerfile
  - name: prod-infra
    manifests:
      kustomize:
        paths:
          - infra/k8s/apps/ticketing/overlays/prod-infra
  - name: prod-app
    manifests:
      kustomize:
        paths:
          - infra/k8s/apps/ticketing/overlays/prod-app
  - name: prod-cloud-app
    manifests:
      kustomize:
        paths:
          - infra/k8s/apps/ticketing/overlays/prod-cloud-app
