export type ErrorCode =
  | 'VALIDATION'
  | 'HTTP_METHOD'
  | 'NOT_FOUND'
  | 'INTERNAL'
  | 'BUSINESS_RULE'
  | 'AUTHENTICATION'
  | 'AUTHORIZATION'
  | 'ACCESS_DENIED'
  | 'USER_ACCESS'
  | 'FORBIDDEN'
  | 'UNREADABLE'
  | 'VERIFICATION_ATTEMPTS_LIMIT';
