FROM node:24.11.1-slim

WORKDIR /app

RUN npm i -g npm@11.6.2

COPY package.json package-lock.json ./
COPY nx.json tsconfig.base.json ./
COPY eslint.config.mjs ./

ENV HUSKY=0
RUN --mount=type=cache,target=/root/.npm npm ci

COPY apps/client ./apps/client

EXPOSE 3000

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npx", "nx", "run", "client:dev"]