FROM node:24-alpine

WORKDIR /app

# Install deps once
COPY package.json package-lock.json ./
COPY nx.json tsconfig.base.json ./

RUN npm ci

COPY apps/tickets ./apps/tickets
COPY packages/core ./packages/core

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npx", "nx", "run", "tickets:dev"]
