FROM node:24.11.1-slim

WORKDIR /app

RUN npm i -g npm@11.6.2

# Install deps once
COPY package.json package-lock.json ./
COPY nx.json tsconfig.base.json ./

ENV HUSKY=0
RUN --mount=type=cache,target=/root/.npm npm ci

COPY apps/tickets ./apps/tickets
COPY packages/core ./packages/core
COPY packages/nats ./packages/nats
COPY packages/contracts ./packages/contracts

ENV NODE_ENV=development

CMD ["npx", "nx", "run", "tickets:dev"]
