apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing-prod

resources:
  - namespace.yaml
  - app-config.yaml

secretGenerator:
  - name: app-secret
    envs:
      - secrets.generated.env

generatorOptions:
  disableNameSuffixHash: true
