FROM node:24.11.1-slim

WORKDIR /app

RUN npm i -g npm@11.6.2

# Install deps once
COPY package.json package-lock.json ./
COPY nx.json tsconfig.base.json ./

# Per-project manifests for dependency graph
COPY apps/payments/package.json apps/payments/
COPY packages/core/package.json packages/core/
COPY packages/nats/package.json packages/nats/
COPY packages/contracts/package.json packages/contracts/

ENV HUSKY=0
ENV NX_VERBOSE_LOGGING=true
RUN --mount=type=cache,target=/root/.npm npm ci

COPY apps/payments ./apps/payments
COPY packages/core ./packages/core
COPY packages/nats ./packages/nats
COPY packages/contracts ./packages/contracts

ENV NODE_ENV=development
ENV NX_DAEMON=false

RUN npx nx build payments

CMD ["node", "apps/payments/dist/index.cjs"]
