apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: tickets-mongo-data
              mountPath: /data/db
          startupProbe:
            tcpSocket:
              port: 27017
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 27017
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 27017
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: tickets-mongo-data
          persistentVolumeClaim:
            claimName: tickets-mongo-data
