apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing-dev

resources:
  - ../dev-common
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - nats-patch.yaml
  - node-runtime-patch.yaml
  - node-runtime-bootstrap-patch.yaml
  - edge-runtime-patch.yaml
  - data-runtime-patch.yaml
