apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SeniorIgor/Ticketing.git
    targetRevision: master
    path: infra/gitops/production/prod-cloud-app
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
